name: log
description: Console logger for app/package development
version: 0.0.1+2
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  test: ^1.20.0

flutter:
  uses-material-design: true
  generate: true
